Simplify

diff --git a/bin/ssh-add-host b/bin/ssh-add-host
--- a/bin/ssh-add-host
+++ b/bin/ssh-add-host
@@ -3,31 +3,37 @@
 # Create an SSH key and uploads it to the given host
 # Based on https://gist.github.com/1761938
 
-local username=$1
-local hostname=$2
-local identifier=$3
-local port=$4
+main() {
 
-if [[ "$port" == "" ]]; then
-	port="22"
-fi
+	local username=$1
+	local hostname=$2
+	local identifier=$3
+	local port=$4
 
-if [[ "$identifier" == "" ]] || [[ "$username" == "" ]] || [[ "$hostname" == "" ]]; then
-	echo "Usage: ssh-add-host <username> <hostname> <identifier> [port]"
-else
-	header "Generating key..."
-	if [ ! -f "$HOME/.ssh/$identifier.id_rsa" ]; then
-		ssh-keygen -f ~/.ssh/$identifier.id_rsa -C "$USER $(date +'%Y/%m%/%d %H:%M:%S')"
+	if [[ "$port" == "" ]]; then
+		port="22"
 	fi
 
-	if ! grep -Fxiq "host $identifier" "$HOME/.ssh/config"; then
-		echo -e "Host $identifier\n\tHostName $hostname\n\tPort $port\n\tUser $username\n\tIdentityFile ~/.ssh/$identifier.id_rsa" >> ~/.ssh/config
+	if [[ "$identifier" == "" ]] || [[ "$username" == "" ]] || [[ "$hostname" == "" ]]; then
+		echo "Usage: ssh-add-host <username> <hostname> <identifier> [port]"
+	else
+		header "Generating key..."
+		if [ ! -f "$HOME/.ssh/$identifier.id_rsa" ]; then
+			ssh-keygen -f ~/.ssh/$identifier.id_rsa -C "$USER $(date +'%Y/%m%/%d %H:%M:%S')"
+		fi
+
+		if ! grep -Fxiq "host $identifier" "$HOME/.ssh/config"; then
+			echo -e "Host $identifier\n\tHostName $hostname\n\tPort $port\n\tUser $username\n\tIdentityFile ~/.ssh/$identifier.id_rsa" >> ~/.ssh/config
+		fi
+
+		header "Uploading key..."
+		ssh $identifier 'umask 077; mkdir -p .ssh && cat >> ~/.ssh/authorized_keys' < ~/.ssh/$identifier.id_rsa.pub
+
+		tput bold
+		ssh -o PasswordAuthentication=no $identifier true && { tput setaf 2; echo "SSH key added."; } || { tput setaf 1; echo "Failure"; }
+		tput sgr0
 	fi
 
-	header "Uploading key..."
-	ssh $identifier 'umask 077; mkdir -p .ssh && cat >> ~/.ssh/authorized_keys' < ~/.ssh/$identifier.id_rsa.pub
+}
 
-	tput bold
-	ssh -o PasswordAuthentication=no $identifier true && { tput setaf 2; echo "SSH key added."; } || { tput setaf 1; echo "Failure"; }
-	tput sgr0
-fi
+main "$@"
