General improvements

diff --git a/shell/bash_functions b/shell/bash_functions
--- a/shell/bash_functions
+++ b/shell/bash_functions
@@ -1,10 +1,36 @@
 #!/bin/bash
 
 # ------------------------------------------------------------------------------
-# | File System                                                                |
+
+# Simple Calculator
+
+? () {
+
+    local result=''
+
+    #                         default (when --mathlib is used) is 20
+    #                         |
+    result="$( printf "scale=10;%s\n" "$*" | bc --mathlib | tr -d "\\\n" )"
+    #                         remove the tailing "\" and "\n" ─┘
+    #                         (large numbers are printed on multiple lines)
+
+    if [[ "$result" == *.* ]]; then
+        # improve the output for decimal numbers
+        printf "%s" "$result" |
+        sed -e "s/^\./0./"        `# add "0" for cases like ".5"` \
+            -e "s/^-\./-0./"      `# add "0" for cases like "-.5"`\
+            -e "s/0*$//;s/\.$//"   # remove tailing zeros
+    else
+        printf "%s" "$result"
+    fi
+
+    printf "\n"
+
+}
+
 # ------------------------------------------------------------------------------
 
-# Create data URI from a file and copy it to the pasteboard
+# Create data URI from a file
 
 datauri() {
 
@@ -23,6 +49,76 @@ datauri() {
         printf "'%s' is not a file.\n" "$1"
     fi
 
+}
+
+# ------------------------------------------------------------------------------
+
+# Create a .tar.gz archive, using `zopfli`, `pigz` or `gzip` for compression
+
+targz() {
+    local tmpFile="${@%/}.tar";
+    tar -cvf "${tmpFile}" --exclude=".DS_Store" "${@}" || return 1;
+
+    size=$(
+        stat -f"%z" "${tmpFile}" 2> /dev/null; # OS X `stat`
+        stat -c"%s" "${tmpFile}" 2> /dev/null # GNU `stat`
+    );
+
+    local cmd="";
+    if (( size < 52428800 )) && hash zopfli 2> /dev/null; then
+        # the .tar file is smaller than 50 MB and Zopfli is available; use it
+        cmd="zopfli";
+    else
+        if hash pigz 2> /dev/null; then
+            cmd="pigz";
+        else
+            cmd="gzip";
+        fi;
+    fi;
+
+    echo "Compressing .tar using \`${cmd}\`…";
+    "${cmd}" -v "${tmpFile}" || return 1;
+    [ -f "${tmpFile}" ] && rm "${tmpFile}";
+    echo "${tmpFile}.gz created successfully.";
+}
+
+# ------------------------------------------------------------------------------
+
+# Extract archives - use: extract <file>
+
+extract() {
+    if [ -f "$1" ] ; then
+        local filename=$(basename "$1")
+        local foldername="${filename%%.*}"
+        local fullpath=`perl -e 'use Cwd "abs_path";print abs_path(shift)' "$1"`
+        local didfolderexist=false
+        if [ -d "$foldername" ]; then
+            didfolderexist=true
+            read -p "$foldername already exists, do you want to overwrite it? (y/n) " -n 1
+            echo
+            if [[ $REPLY =~ ^[Nn]$ ]]; then
+                return
+            fi
+        fi
+        mkdir -p "$foldername" && cd "$foldername"
+        case $1 in
+            *.tar.bz2) tar xjf "$fullpath" ;;
+            *.tar.gz) tar xzf "$fullpath" ;;
+            *.tar.xz) tar Jxvf "$fullpath" ;;
+            *.tar.Z) tar xzf "$fullpath" ;;
+            *.tar) tar xf "$fullpath" ;;
+            *.taz) tar xzf "$fullpath" ;;
+            *.tb2) tar xjf "$fullpath" ;;
+            *.tbz) tar xjf "$fullpath" ;;
+            *.tbz2) tar xjf "$fullpath" ;;
+            *.tgz) tar xzf "$fullpath" ;;
+            *.txz) tar Jxvf "$fullpath" ;;
+            *.zip) unzip "$fullpath" ;;
+            *) echo "'$1' cannot be extracted via extract()" && cd .. && ! $didfolderexist && rm -r "$foldername" ;;
+        esac
+    else
+        echo "'$1' is not a valid file"
+    fi
 }
 
 # ------------------------------------------------------------------------------
@@ -108,9 +204,9 @@ tre() {
 
 # ------------------------------------------------------------------------------
 
-# List file-system permissions
+# File-system permissions listed
 
-lsp() {
+file-permissions() {
   ls -l "$@" | awk '{
     k=0;
     for(i=0;i<=8;i++)
@@ -177,107 +273,23 @@ o() {
 }
 
 # ------------------------------------------------------------------------------
-# | Miscellaneous                                                              |
-# ------------------------------------------------------------------------------
 
-# Simple Calculator
+# whois a domain or a URL
 
-? () {
+whois() {
 
-    local result=''
-
-    #                         default (when --mathlib is used) is 20
-    #                         |
-    result="$( printf "scale=10;%s\n" "$*" | bc --mathlib | tr -d "\\\n" )"
-    #                         remove the tailing "\" and "\n" ─┘
-    #                         (large numbers are printed on multiple lines)
-
-    if [[ "$result" == *.* ]]; then
-        # improve the output for decimal numbers
-        printf "%s" "$result" |
-        sed -e "s/^\./0./"        `# add "0" for cases like ".5"` \
-            -e "s/^-\./-0./"      `# add "0" for cases like "-.5"`\
-            -e "s/0*$//;s/\.$//"   # remove tailing zeros
-    else
-        printf "%s" "$result"
+    local domain=$(echo "$1" | awk -F/ '{print $3}') # get domain from URL
+    if [ -z $domain ] ; then
+        domain=$1
     fi
+    echo "Getting whois record for: $domain …"
 
-    printf "\n"
-
+    # avoid recursion
+    #      |         this is the best whois server
+    #      |                      |                  strip extra fluff
+    /usr/bin/whois -h whois.internic.net $domain | sed '/NOTICE:/q'
 }
 
-# ------------------------------------------------------------------------------
-
-# Extract archives - use: extract <file>
-
-extract() {
-    if [ -f "$1" ] ; then
-        local filename=$(basename "$1")
-        local foldername="${filename%%.*}"
-        local fullpath=`perl -e 'use Cwd "abs_path";print abs_path(shift)' "$1"`
-        local didfolderexist=false
-        if [ -d "$foldername" ]; then
-            didfolderexist=true
-            read -p "$foldername already exists, do you want to overwrite it? (y/n) " -n 1
-            echo
-            if [[ $REPLY =~ ^[Nn]$ ]]; then
-                return
-            fi
-        fi
-        mkdir -p "$foldername" && cd "$foldername"
-        case $1 in
-            *.tar.bz2) tar xjf "$fullpath" ;;
-            *.tar.gz) tar xzf "$fullpath" ;;
-            *.tar.xz) tar Jxvf "$fullpath" ;;
-            *.tar.Z) tar xzf "$fullpath" ;;
-            *.tar) tar xf "$fullpath" ;;
-            *.taz) tar xzf "$fullpath" ;;
-            *.tb2) tar xjf "$fullpath" ;;
-            *.tbz) tar xjf "$fullpath" ;;
-            *.tbz2) tar xjf "$fullpath" ;;
-            *.tgz) tar xzf "$fullpath" ;;
-            *.txz) tar Jxvf "$fullpath" ;;
-            *.zip) unzip "$fullpath" ;;
-            *) echo "'$1' cannot be extracted via extract()" && cd .. && ! $didfolderexist && rm -r "$foldername" ;;
-        esac
-    else
-        echo "'$1' is not a valid file"
-    fi
-}
-
-# ------------------------------------------------------------------------------
-
-# Create a .tar.gz archive, using `zopfli`, `pigz` or `gzip` for compression
-
-targz() {
-    local tmpFile="${@%/}.tar";
-    tar -cvf "${tmpFile}" --exclude=".DS_Store" "${@}" || return 1;
-
-    size=$(
-        stat -f"%z" "${tmpFile}" 2> /dev/null; # OS X `stat`
-        stat -c"%s" "${tmpFile}" 2> /dev/null # GNU `stat`
-    );
-
-    local cmd="";
-    if (( size < 52428800 )) && hash zopfli 2> /dev/null; then
-        # the .tar file is smaller than 50 MB and Zopfli is available; use it
-        cmd="zopfli";
-    else
-        if hash pigz 2> /dev/null; then
-            cmd="pigz";
-        else
-            cmd="gzip";
-        fi;
-    fi;
-
-    echo "Compressing .tar using \`${cmd}\`…";
-    "${cmd}" -v "${tmpFile}" || return 1;
-    [ -f "${tmpFile}" ] && rm "${tmpFile}";
-    echo "${tmpFile}.gz created successfully.";
-}
-
-# ------------------------------------------------------------------------------
-# | Network                                                                    |
 # ------------------------------------------------------------------------------
 
 # Start an HTTP server from a directory, optionally specifying the port
@@ -347,59 +359,6 @@ httpd.serve_forever()
 
 # ------------------------------------------------------------------------------
 
-# whois a domain or a URL
-
-whois() {
-
-    local domain=$(echo "$1" | awk -F/ '{print $3}') # get domain from URL
-    if [ -z $domain ] ; then
-        domain=$1
-    fi
-    echo "Getting whois record for: $domain …"
-
-    # avoid recursion
-    #      |         this is the best whois server
-    #      |                      |                  strip extra fluff
-    /usr/bin/whois -h whois.internic.net $domain | sed '/NOTICE:/q'
-}
-
-# ------------------------------------------------------------------------------
-# | Search                                                                     |
-# ------------------------------------------------------------------------------
-
-# Search history
-
-qh() {
-    #           enable colors for pipe
-    #           │  ("--color=auto" enables colors only if
-    #           │  the output is in the terminal)
-    grep --color=always "$*" "$HISTFILE" |       less -RX
-    # display ANSI color escape sequences in raw form ─┘│
-    #       don't clear the screen after quitting less ─┘
-}
-
-# ------------------------------------------------------------------------------
-
-# Search for text within the current directory
-
-qt() {
-    grep -ir --color=always "$*" . | less -RX
-    #      -- search all files under each directory, recursively
-    #     --- ignore case
-}
-
-# ------------------------------------------------------------------------------
-
-# Search and relace text within the current directory
-
-qr() {
-    grep -r -l "$1" . | sort | uniq | xargs perl -e "s/$1/$2/" -pi
-}
-
-# ------------------------------------------------------------------------------
-# | Text Processing                                                            |
-# ------------------------------------------------------------------------------
-
 # Human redable file size
 # (because `du -h` doesn't cut it for me)
 
@@ -430,4 +389,37 @@ hrfs() {
     sed -e ":l; s/\([0-9]\)\([0-9]\{3\}\)/\1,\2/; t l"
     #                          -- add commas to the numbers
     #                             (changes "1023.2 KB" to "1,023.2 KB")
+}
+
+# ------------------------------------------------------------------------------
+
+# Search history
+
+qh() {
+
+    #           ┌─ enable colors for pipe
+    #           │  ("--color=auto" enables colors only if
+    #           │  the output is in the terminal)
+    grep --color=always "$*" "$HISTFILE" |       less -RX
+    # display ANSI color escape sequences in raw form ─┘│
+    #       don't clear the screen after quitting less ─┘
+}
+
+# ------------------------------------------------------------------------------
+
+# Search for text within the current directory
+
+qt() {
+
+    grep -ir --color=always "$*" . | less -RX
+    #     │└─ search all files under each directory, recursively
+    #     └─ ignore case
+}
+
+# ------------------------------------------------------------------------------
+
+# Search + Relace text within the current directory
+
+qr() {
+    grep -r -l "$1" . | sort | uniq | xargs perl -e "s/$1/$2/" -pi
 }
