revamp: macOS and Ubuntu support

diff --git a/shell/bash_prompt b/shell/bash_prompt
--- a/shell/bash_prompt
+++ b/shell/bash_prompt
@@ -1,114 +1,117 @@
 #!/bin/bash
 
-# ------------------------------------------------------------------------------
-# | Colors                                                                     |
-# ------------------------------------------------------------------------------
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
 enable_color_support() {
 
-    if infocmp xterm-256color &> /dev/null; then
-        export TERM='xterm-256color'
+    if [[ $COLORTERM == gnome-* && $TERM == xterm ]] \
+        && infocmp gnome-256color &> /dev/null; then
+        export TERM="gnome-256color"
+    elif infocmp xterm-256color &> /dev/null; then
+        export TERM="xterm-256color"
     fi
 
-    alias ls='ls -G' # or CLICOLOR=1
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+    # Load OS specific color support
+
+    . "$(get_os)/bash_colors"
 
 }
 
-set_ls_colors() {
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-    # There are several different implementations of color for ls:
-
-    # --------------------------------------------------------------------------
-    # | FreeBSD / OS X                                                         |
-    # --------------------------------------------------------------------------
-
-    #  - `ls` displays colors if the `-G` option is passed or if
-    #    the `CLICOLOR` environment variable is set
-    #
-    #  - the actual colors are configured through the `LSCOLORS`
-    #    environment variable (built-in defaults are used if this
-    #    variable is not set)
-
-    LSCOLORS=''
-
-    LSCOLORS+='gx' # Directory
-    LSCOLORS+='fx' # Symbolic link
-    LSCOLORS+='bE' # Socket
-    LSCOLORS+='aE' # Pipe
-    LSCOLORS+='Bx' # Executable
-    LSCOLORS+='xE' # Block special
-    LSCOLORS+='hE' # Character special
-    LSCOLORS+='hB' # Executable with setuid bit set
-    LSCOLORS+='aD' # Executable with setgid bit set
-    LSCOLORS+='aC' # Directory writable to others, with sticky bit
-    LSCOLORS+='aD' # Directory writable to others, without sticky bit
-
-    export LSCOLORS
-
-}
-
-# ------------------------------------------------------------------------------
-# | Prompts                                                                    |
-# ------------------------------------------------------------------------------
-
-# Note: Don't break this function into smaller, more specialized ones
+# [!] Don't break this function into smaller, more specialized ones
 # as you will only pollute the global space even more (this function
-# cannot be unset due to the fact that it's called every time the prompt
-# string is shown)
+# cannot be unset because it's called every time the prompt string
+# is shown)
 
 get_git_repository_details() {
 
-    local branchName=''
-    local tmp=''
+    local branchName=""
+    local tmp=""
 
-    # --------------------------------------------------------------------------
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
     # Check if the current directory is in a Git repository
-    [ "$(git rev-parse &>/dev/null; printf $?)" -ne 0 ] && return
+
+    ! git rev-parse &>/dev/null \
+        && return
+
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
     # Check if in `.git/` directory (some of the following
     # checks don't make sense/won't work in the `.git` directory)
-    [ "$(git rev-parse --is-inside-git-dir)" == "true" ] && return
+
+    [ "$(git rev-parse --is-inside-git-dir)" == "true" ] \
+        && return
+
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
     # Check for uncommitted changes in the index
-    if ! $(git diff --quiet --ignore-submodules --cached); then
+
+    if ! git diff --quiet --ignore-submodules --cached; then
         tmp="$tmp+";
     fi
 
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
     # Check for unstaged changes
-    if ! $(git diff-files --quiet --ignore-submodules --); then
+
+    if ! git diff-files --quiet --ignore-submodules --; then
         tmp="$tmp!";
     fi
 
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
     # Check for untracked files
+
     if [ -n "$(git ls-files --others --exclude-standard)" ]; then
         tmp="$tmp?";
     fi
 
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
     # Check for stashed files
-    if $(git rev-parse --verify refs/stash &>/dev/null); then
+
+    if git rev-parse --verify refs/stash &>/dev/null; then
         tmp="$tmp$";
     fi
 
-    [ -n "$tmp" ] && tmp=" [$tmp]"
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
+    [ -n "$tmp" ] \
+        && tmp=" [$tmp]"
 
-    branchName="$( printf "$( git rev-parse --abbrev-ref HEAD 2> /dev/null \
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+    branchName="$( printf "%s" "$( git rev-parse --abbrev-ref HEAD 2> /dev/null \
         || git rev-parse --short HEAD 2> /dev/null \
-        || printf " (unknown)" )" | \
-        tr -d "\n" )"
+        || printf " (unknown)" )" | tr -d "\n" )"
 
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
     printf "%s" "$1$branchName$tmp"
 
 }
 
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
 set_prompts() {
 
-    local black='' blue='' bold='' cyan='' green='' orange='' \
-          purple='' red='' reset='' white='' yellow=''
+    # local black=""
+    # local blue=""
+    local bold=""
+    local cyan=""
+    local green=""
+    # local orange=""
+    # local purple=""
+    # local red=""
+    local reset=""
+    local white=""
+    local yellow=""
 
-    # --------------------------------------------------------------------------
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
     if [ -x /usr/bin/tput ] && tput setaf 1 &> /dev/null; then
 
@@ -120,45 +123,46 @@ set_prompts() {
         # Solarized colors
         # https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized#the-values
 
-        black=$(tput setaf 0)
-        blue=$(tput setaf 33)
+        # black=$(tput setaf 0)
+        # blue=$(tput setaf 33)
         cyan=$(tput setaf 37)
         green=$(tput setaf 64)
         orange=$(tput setaf 166)
-        purple=$(tput setaf 125)
-        red=$(tput setaf 124)
+        # purple=$(tput setaf 125)
+        # red=$(tput setaf 124)
         white=$(tput setaf 15)
         yellow=$(tput setaf 136)
 
     else
 
-        bold=''
+        bold="\e[1m"
         reset="\e[0m"
 
-        black="\e[1;30m"
-        blue="\e[1;34m"
+        # black="\e[1;30m"
+        # blue="\e[1;34m"
         cyan="\e[1;36m"
         green="\e[1;32m"
         orange="\e[1;33m"
-        purple="\e[1;35m"
-        red="\e[1;31m"
+        # purple="\e[1;35m"
+        # red="\e[1;31m"
         white="\e[1;37m"
         yellow="\e[1;33m"
 
     fi
 
-    # --------------------------------------------------------------------------
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
     # Prompt Statement variables
     # http://ss64.com/bash/syntax-prompt.html
 
-    # --------------------------------------------------------------------------
-    # | PS1 - Default interactive prompt                                       |
-    # --------------------------------------------------------------------------
+    # ------------------------------------------------------------------
+    # | PS1 - Default interactive prompt                               |
+    # ------------------------------------------------------------------
 
     PS1="\[\033]0;\W\007\]"         # Terminal title (set to the
                                     # current working directory)
-    PS1+="\[$bold\]\n"              # Newline
+
+    PS1+="\[$bold\]"
     PS1+="\[$orange\]\u"            # Username
     PS1+="\[$white\]@"
     PS1+="\[$yellow\]\h"            # Host
@@ -170,28 +174,28 @@ set_prompts() {
 
     export PS1
 
-    # --------------------------------------------------------------------------
-    # | PS2 - Continuation interactive prompt                                  |
-    # --------------------------------------------------------------------------
+    # ------------------------------------------------------------------
+    # | PS2 - Continuation interactive prompt                          |
+    # ------------------------------------------------------------------
 
-    PS2='⚡ '
+    PS2="⚡ "
 
     export PS2
 
-    # --------------------------------------------------------------------------
-    # | PS4 - Debug prompt                                                     |
-    # --------------------------------------------------------------------------
+    # ------------------------------------------------------------------
+    # | PS4 - Debug prompt                                             |
+    # ------------------------------------------------------------------
 
     # e.g:
     #
     # The GNU `date` command has the `%N` interpreted sequence while
-    # other implementations don't (on OS X `gdate` can be used instead
-    # of the native `date` if the `coreutils` package was installed)
+    # other implementations don't (on macOS `gdate` can be used instead
+    # of the native `date` if the `coreutils` package has been installed)
     #
     # local dateCmd=""
     #
     # if [ "$(date +%N)" != "N" ] || \
-    #    [ ! -x "$(command -v 'gdate')" ]; then
+    #    [ ! -x "$(command -v "gdate")" ]; then
     #    dateCmd="date +%s.%N"
     # else
     #    dateCmd="gdate +%s.%N"
@@ -217,25 +221,19 @@ set_prompts() {
 
 }
 
-# ------------------------------------------------------------------------------
-# | Main                                                                       |
-# ------------------------------------------------------------------------------
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
 main() {
-
     enable_color_support
-    set_ls_colors
     set_prompts
-
 }
 
 main
 
-# ------------------------------------------------------------------------------
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-# Unset functions in order to not pollute the global space
+# Cleanup
 
 unset -f enable_color_support
 unset -f main
-unset -f set_ls_colors
 unset -f set_prompts
